// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test_1_(log_in+system_start)', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test_1_(log_in+system_start)', async function() {
    await driver.get("https://robots.unboxrobotics.com/sc")
    await driver.manage().window().setRect({ width: 727, height: 910 })
    await driver.findElement(By.name("email")).sendKeys("super_user")
    await driver.findElement(By.name("password")).sendKeys("ubr_admin@2023")
    await driver.findElement(By.css(".sc-hKMtDE")).click()
    await driver.findElement(By.css(".sc-gITdGB")).click()
    await driver.findElement(By.css(".gOmHPS")).click()
    await driver.findElement(By.css(".sc-fIauvf > div > div")).click()
    await driver.findElement(By.css(".sc-bczSft:nth-child(8) > .sc-gsnScm:nth-child(1)")).click()
  })
})
