// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test_2_(system_start+bot_commisioning)', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test_2_(system_start+bot_commisioning)', async function() {
    await driver.get("https://robots.unboxrobotics.com/sc/home")
    await driver.findElement(By.css(".sc-gITdGB")).click()
    await driver.findElement(By.css(".sc-bczSft:nth-child(8) > .sc-gsnScm:nth-child(1)")).click()
    await driver.findElement(By.css(".sc-bczSft:nth-child(8) > .sc-gsnScm:nth-child(2)")).click()
  })
})
